// This file was generated by the XState CLI, please do not edit it manually.
import { createMachine } from "xstate";

const machine = createMachine(
  {
    context: {
      count: 0,
    },
    id: "counter",
    meta: {
      gitHubUrl:
        "https://github.com/laurakalbag/stately-7guis/blob/29a249664b735ef57ad757e35642c648a2ce7f74/src/machines/counterMachine.ts",
    },
    on: {
      INCREMENT: {
        target: "#counter",
        actions: {
          type: "increment",
        },
      },
    },
    types: {
      events: {} as { type: "INCREMENT" },
      context: {} as { count: number },
    },
  },
  {
    actions: {
      increment: ({ context, event }) => {},
    },
    actors: {},
    guards: {},
    delays: {},
  }
);
export const skyConfig = {
  actorId: "5ad4ca32-3d66-4089-8803-11508ee18005",
  machine,
};
